version: '3.8'

services:
  betting_db:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=${TZ}
    ports:
      - "3308:3306"
    volumes:
      - betting_db_volumes:/var/lib/mysql
      - ./script/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      betting-net:

  betting_webapp:
    depends_on:
      - betting_db
    image: duyna5/bf5-betting
    restart: on-failure
    environment:
      - TZ=${TZ}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=betting_db:3306
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "8080:8080"
    volumes:
      - .m2:/root/.m2
    networks:
      betting-net:
    stdin_open: true
    tty: true

networks:
  betting-net:

volumes:
  betting_db_volumes:
